# Generated by Django 5.1.7 on 2025-05-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetweb', '0010_carrito_orden_userprofile_created_at_ordenitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
