# Generated by Django 5.1.7 on 2025-06-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetweb', '0013_listadeseos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ordenitem',
            name='precio_unitario',
            field=models.IntegerField(),
        ),
    ]
